import React from 'react';
import { alpha, useTheme } from '@mui/material/styles';
import Box from '@mui/material/Box';
import Accordion from '@mui/material/Accordion';
import AccordionSummary from '@mui/material/AccordionSummary';
import Typography from '@mui/material/Typography';
import AccordionDetails from '@mui/material/AccordionDetails';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import mixpanel from 'mixpanel-browser';
import { Link } from '@mui/material';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';



const referrer = document.referrer !== '' ? document.referrer : 'Unknown';
const handleGetThinksyClick = () => {
  mixpanel.track('Clicked FAQ Email Button', {
    'Referrer': referrer
  })
};

const handleFaqClick = (title, expanded) => {
  mixpanel.track('Clicked FAQ Question', {
    'title': title,
    'expanded': expanded
  })
};


const to = "calli@thinksy.app";
const subject = "Gimme Thinksy!";
const body = "Hey Calli, I'm interested in trying out Thinksy! Can we set up some time for a demo?";
const mailtoLink = `mailto:${to}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;

const Faq = () => {
  const theme = useTheme();
  return (
    <Box>
      <Box marginBottom={4}>
        <Box
          component={Typography}
          fontWeight={700}
          variant={'h3'}
          align={'center'}
        >
          Frequently Asked Questions
        </Box>
      </Box>
      <Box marginBottom={4}>
        {[
          {
            title: 'What happens after I sign up for Thinksy?',
            subtitle:
              'After signing up for Thinksy you will receive a confirmation email with a link to schedule an on-boarding call with one of our co-founders. During the on-boarding call we will share screens and walk you through the steps to add Thinksy to your Slack workspace, integrate your apps, and test your first Thinksy summary. You\'ll also gain access to the exclusive Thinksy support channel for on-going feedback loop.',
          },
          {
            title: 'What is the Thinksy support channel?',
            subtitle:
              'The Thinksy support channel is an exclusive Slack Connect channel for users to access immediate support, give feedback, chat with other Thinksy users and more. It is available only to premium users of Thinksy.',
          },
          {
            title: 'Can I cancel anytime?',
            subtitle:
              'Yes, you can cancel anytime, there is no long term obligation. Thinksy is billed month to month so if you choose to cancel, your Thinksy account will be deactivated on the last day before your next billing period.',
          },
          {
            title: 'What is your money back guarantee?',
            subtitle:
              'If you are not satisfied with Thinksy, we will refund you for the amount you paid for Thinksy up to three (3) months. To help us learn & grow as a company we will request an exist interview so we can continually improve.',
          },
          {
            title: 'How do I know my data is secure with Thinksy?',
            subtitle:
              'We take the security of your data very seriously. Please email our CTO for details on how we keep your data safe eden@enhancenothing.com',
          },
          {
            title: 'How does Thinksy work?',
            subtitle:
              'Thinksy works by fetching data from the apps you\'ve connected and feeds them into the OpenAI fine-tuning API to summarize your work across platforms. We never store data retrieved from your connected integrations.\n\nWe use OpenAI APIs and not the commercially available models (i.e. ChatGPT), audited for SOC 2 compliance and does not use your data for machine training. Read OpenAI\'s full privacy statement here: https://openai.com/enterprise-privacy',
          },
          {
            title: 'Can I change the results I get from Thinksy?',
            subtitle:
              'At this time, custom prompts are only available to Enterprise customers. For Standard and Premium plans, the results generated by Thinksy will not change unless the input data is updated',
          },
          {
            title: 'How do I review a coworker?',
            subtitle:
              'To run reports on coworkers and other users, upgrade to Premium.',
          },
          {
            title: 'When will you add more integrations?',
            subtitle:
              'While there is no set schedule for new features or new integrations we are continually iterating and improving Thinksy and notify those on our mailing list of the latest updates as soon as they\'re available.',
          },
        ].map((item, i) => (
          <Box
            component={Accordion}
            key={i}
            padding={1}
            marginBottom={i === item.length - 1 ? 0 : 2}
            borderRadius={`${theme.spacing(1)} !important`}
            onChange={(event, expanded) => handleFaqClick(item.title, expanded)}
            sx={{
              '&::before': {
                display: 'none',
              },
            }}
          >
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              aria-controls="panel1a-content"
              id={`panel1a-header--${i}`}
            >
              <Typography fontWeight={'medium'}>{item.title}</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography color="text.secondary">{item.subtitle}</Typography>
            </AccordionDetails>
          </Box>
        ))}
      </Box>
      <Grid container spacing={2} justifyContent="center" alignItems="center">
        <Grid item>
          <Box
            component={Typography}
            fontWeight={700}
            variant={'h6'}
            align={'center'}
            color="textSecondary"
          >
            Still have questions?
          </Box>
        </Grid>
        <Grid item>
          <Link href={mailtoLink} target="_blank" underline="none">
            <Box
              component={Button}
              variant="contained"
              color={theme.palette.primary.dark}
              size="large"
              type="submit"
              style={{ minWidth: '230px', backgroundColor: theme.palette.secondary.main }}
              margin={1}
              onClick={handleGetThinksyClick}
            >
              Send us an email
            </Box>
          </Link>
        </Grid>
    </Grid>

    </Box>
  );
};

export default Faq;
